### ISSUE TITLE
How to run this

### ISSUE THREAD

**Issue by MapGuy11** [Zeexel/OpenStar#1]
Hello,
I am new to this type of development. Though I am really interested in your project I have everything cloned and I think everything is installed for OpenFL and HaxelFlixel. I was just wondering how I run the project. Just a single command I assume thanks for your help! BTW saw the video and love it!

**Comment by Zeexel** [comment]
> Hello, I am new to this type of development. Though I am really interested in your project I have everything cloned and I think everything is installed for OpenFL and HaxelFlixel. I was just wondering how I run the project. Just a single command I assume thanks for your help! BTW saw the video and love it!

Hi! I'll be including build instructions in the README.md soon. I haven't gotten around to it yet because the method of creating the timers for the PresentationState is made with a slightly modified version of the FlxTimer class in HaxeFlixel

Might I ask what operating system you're running? I might just be able to provide some one-stop instructions here if you're running a Linux distribution or macOS.

Also, I'm glad you liked the video! It's a very indev build of it and it uses OBS for chroma keying, so it may change eventually in the future.
